version: '3.8'

services:
  frontend:
    build:
      context: Frontend
      args:
        - VITE_API_URL=http://reactschool.site/api
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://reactschool.site/api
    # depends_on:
      # - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/reactschool
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    command: >
      sh -c "uvicorn app:app --host 0.0.0.0 --port 8000"
    restart:
      always

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reactschool
    